name: algo_trade
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  web_socket_channel: 2.4.0
  get_storage: 2.1.1
  fluttertoast: 8.2.1
  intl: 0.18.1
  pie_chart: 5.3.2
  fl_chart: 0.63.0
  firebase_core: 2.14.0
  firebase_messaging: 14.6.4
  flutter_local_notifications: 15.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

